title: 완이의 웹으로 먹고살기

email: me@wani.kr

markdown: redcarpet
redcarpet:
  extensions: [
    "strikethrough",
    "footnotes",
    "autolink",
    "underline"
  ]

permalink: /:categories/:title
paginate_path: /page/:num

paginate: 10

author:
  twitter: wan2land
  github: wan2land

gems: [
    'jekyll-less'
  ]