title: 완이의 웹으로 먹고살기

email: im@wani.kr

markdown: kramdown

permalink: /posts/:year/:month/:day/:title/
paginate_path: /posts/page/:num

paginate: 10

author:
  twitter: wan2land
  github: wan2land

sass:
    sass_dir: _scss
    style: compressed
