title: 완이의 웹으로 먹고살기

email: me@wani.kr

description: > # this means to ignore newlines until "baseurl:"
  개발 6년차,  Front-End로 시작했지만 한걸음씩 Back-End쪽으로 걸음마 중.

markdown: redcarpet
permalink: /:categories/:title
paginate_path: /page/:num

paginate: 10

author:
  twitter: wan2land
  github: wan2land

